version: '3'


services:
  db:
    image: mysql
    restart: always
    volumes:
      - ./data/db:/var/lib/mysql
    ports:
      - 3306:3306
   
    environment:
      MYSQL_USER: emp
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: sakura
      MYSQL_PASSWORD: emp2
      
  
  adminer:
    image: adminer
    restart: always
    ports:
    - 8080:8080

    
